server:
  port: 80

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          prefer-ip: true  #??ip??

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
     exposure:
      include: "*"